ALTER TABLE "WITS_Config"
ADD COLUMN "plotScaleLeft" DECIMAL(16,6),
ADD COLUMN "plotScaleRight" DECIMAL(16,6),
ADD COLUMN "lineColor" VARCHAR(20),
ADD COLUMN "wrapColor" VARCHAR(20),
ADD COLUMN "depthTrackingMode" VARCHAR(50) NOT NULL DEFAULT 'bit_depth',
ADD COLUMN "depthTrackingField" VARCHAR(100) NOT NULL DEFAULT 'depth',
ADD COLUMN "dataInputValue" DECIMAL(16,6);

INSERT INTO "WITS_Config" (
  "witsId",
  "name",
  "mappedField",
  "units",
  "decimalPlaces",
  "scaleFactor",
  "biasOffset",
  "sensorToBitSpacing",
  "plotScaleLeft",
  "plotScaleRight",
  "lineColor",
  "wrapColor",
  "depthTrackingMode",
  "depthTrackingField",
  "alarmEnabled",
  "alarmMin",
  "alarmMax",
  "dataSource",
  "dataInputValue",
  "sendToAuxPort",
  "sendToRigWitsPort",
  "doNotRepeat",
  "lasTag",
  "lasDescription",
  "lasFilter",
  "enableLogging"
)
VALUES (
  '0824',
  'Gamma API',
  'gammaRay',
  'API',
  0,
  1,
  0,
  37,
  0,
  150,
  '#0000ff',
  '#ff0000',
  'bit_depth',
  'depth',
  false,
  -9999.9,
  99999.9,
  'serial_port_wits',
  70,
  false,
  true,
  false,
  'gamma',
  'Gamma API reading',
  0,
  true
)
ON CONFLICT ("witsId") DO UPDATE SET
  "name" = EXCLUDED."name",
  "mappedField" = EXCLUDED."mappedField",
  "units" = EXCLUDED."units",
  "decimalPlaces" = EXCLUDED."decimalPlaces",
  "scaleFactor" = EXCLUDED."scaleFactor",
  "biasOffset" = EXCLUDED."biasOffset",
  "sensorToBitSpacing" = EXCLUDED."sensorToBitSpacing",
  "plotScaleLeft" = EXCLUDED."plotScaleLeft",
  "plotScaleRight" = EXCLUDED."plotScaleRight",
  "lineColor" = EXCLUDED."lineColor",
  "wrapColor" = EXCLUDED."wrapColor",
  "depthTrackingMode" = EXCLUDED."depthTrackingMode",
  "depthTrackingField" = EXCLUDED."depthTrackingField",
  "alarmEnabled" = EXCLUDED."alarmEnabled",
  "alarmMin" = EXCLUDED."alarmMin",
  "alarmMax" = EXCLUDED."alarmMax",
  "dataSource" = EXCLUDED."dataSource",
  "dataInputValue" = EXCLUDED."dataInputValue",
  "sendToAuxPort" = EXCLUDED."sendToAuxPort",
  "sendToRigWitsPort" = EXCLUDED."sendToRigWitsPort",
  "doNotRepeat" = EXCLUDED."doNotRepeat",
  "lasTag" = EXCLUDED."lasTag",
  "lasDescription" = EXCLUDED."lasDescription",
  "lasFilter" = EXCLUDED."lasFilter",
  "enableLogging" = EXCLUDED."enableLogging";
